### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by HeyItsGwen**
Pull feature branch to master for code review

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Team,👋
You have done a great job with this project so far.💪
Here are a few changes we have to make to get this project approved.🙂

* [ ] Let us fix the warnings returned by the[ validator ](https://validator.w3.org) after uploading the index file.🙂 

* [ ] Let us add centered links to our footer(content is not important)

### That is it Guys, Kindly make these changes and submit the project for review

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.
#### Happy coding🙂

**Comment by HeyItsGwen** [comment]
There are no errors when validating?

**Comment by Anna-Myzukina** [comment]
### Hi Team!  Great job!  

Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!


Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.

### Make these changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by HeyItsGwen** [comment]
This is the validator for both the HTML and CSS, copied directly from the repo that you're reviewing. It's green, saying no errors were found. What needs fixing?

noErrorsCSS
noErrors

**Comment by HeyItsGwen** [comment]
Validating by upload gives a different result than doing it by copy-paste, fixed the error.

**Comment by Anna-Myzukina** [comment]
* Here missed meta charset="UTF-8" in HTML file.
* The value of the attribute should be in double quotes.

**Comment by HeyItsGwen** [comment]
Yup we fixed it, see above comment

**Comment by Anna-Myzukina** [comment]
When you finish changes submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by HeyItsGwen** [comment]
I submitted another code request previously, it says I can't submit another, because it's still open.

**Review by Forison — APPROVED** [review]
# Good Job team,
Kindly merge to master
## The project is approved.
#### Happy coding

**Comment by aracelicaes** [comment]
Merging pull request and master branch.

**Pull request merged**
